### ISSUE TITLE
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?

### ISSUE THREAD

**Issue by birchb1024** [gocd/gocd-ldap-authorization-plugin#15]
Hi,

We're connecting to Microsoft Active Directory. We are recently seeing this error on every ldap transaction. Sometimes the application wont let people log in at all and a restart is requried. My hunch is these exceptions are borking something in GoCD by not cleaning up. 

What should I look at next? 

Regards,
Bill

`2020-08-07 17:29:37,042 DEBUG [NioProcessor-16] LdapPlugin:51 - received a NoD, closing everything
2020-08-07 17:29:37,042 DEBUG [qtp662822946-15] LdapPlugin:46 - [Authenticate] Resolving roles for user: `user` using auth_config: `configname`.
2020-08-07 17:29:37,042 DEBUG [NioProcessor-16] LdapPlugin:51 - Unexpected exception from SSLEngine.closeInbound().
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1647)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1615)
        at sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:1542)
        at org.apache.mina.filter.ssl.SslHandler.destroy(SslHandler.java:213)
        at org.apache.mina.filter.ssl.SslFilter.sessionClosed(SslFilter.java:473)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionClosed(DefaultIoFilterChain.java:504)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$900(DefaultIoFilterChain.java:48)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.sessionClosed(DefaultIoFilterChain.java:927)
        at org.apache.mina.core.filterchain.IoFilterAdapter.sessionClosed(IoFilterAdapter.java:88)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionClosed(DefaultIoFilterChain.java:504)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireSessionClosed(DefaultIoFilterChain.java:497)
        at org.apache.mina.core.service.IoServiceListenerSupport.fireSessionDestroyed(IoServiceListenerSupport.java:245)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.removeNow(AbstractPollingIoProcessor.java:587)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.removeSessions(AbstractPollingIoProcessor.java:544)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$800(AbstractPollingIoProcessor.java:68)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1128)
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by arvindsv** [comment]
This looks like something to do with the network connection. I think this plugin doesn't hold much state internally for it to be messed up.

1. Can you paste more of the logs? If I search for: "Inbound closed before receiving peer's close_notify: possible truncation attack?", there [are some](https://groups.google.com/forum/#!topic/search-guard/IIe_RUGBZI4) who say that it can be ignored and is harmless. So, maybe there is something of intrest in the rest of the logs.

2. Which version of this plugin are you running? Messages such as this: "LdapPlugin:46 - [Authenticate] Resolving roles for user:" don't seem to match with respect to line numbers.

**Comment by chadlwilson** [comment]
Closing stale issue. Please let us know if you're able to supply more information.
